### ISSUE TITLE
GHC 8.10 support

### ISSUE THREAD

**Issue by sjakobi** [haskell-hvr/cryptohash-sha512#4]
This package currently has a bound `base < 4.14`.

BTW, is it still recommended to use this package, or are there better replacements like possibly [`hashing`](http://hackage.haskell.org/package/hashing)? I'm not very familiar with the Haskell crypto ecosystem, so I'd appreciate any advice! :)

**Comment by juhp** [comment]
This blocks hnix-store-core-0.3 on 8.10

cc @haskell-nix

**Comment by sjakobi** [comment]
This was addressed by a Hackage Trustee: http://hackage.haskell.org/package/cryptohash-sha512-0.11.100.1/revisions/
