### ISSUE TITLE
Please, archive the project

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-hvr/cryptohash-sha512#6]
Just noted that the whole `cryptohash*` family is deprecated: https://github.com/vincenthz/hs-cryptohash#readme in favor of `cryptonite` family.

**Comment by Anton-Latukha** [comment]
Just noted that the whole `cryptohash*` family is deprecated: https://github.com/vincenthz/hs-cryptohash#readme in favor of `cryptonite` family.

**Comment by amesgen** [comment]
I was also confused by this prevously: This package is *not* deprecated, it was rather specifically created due to `cryptohash` being deprecated. From the package description:

> This package has been forked off `cryptohash-0.11.7` because the `cryptohash` package has been deprecated and so this package continues to satisfy the need for a lightweight package providing the SHA512 hash algorithm without any dependencies on packages other than `base` and `bytestring`.

So I think this issue can be closed.

**Comment by Anton-Latukha** [comment]
Yes, you are right, forgot that I created this.

But, nevertheless. The project is alive only because of Hackage trustees updating the bounds to it, `cryptohash-*` family seems to go away rather sooner than later.
The creation of many package is the right approach to provide the best support: https://nikita-volkov.github.io//internal-convention-is-a-mistake/
